syntax = "proto3";

package pin_proxy;


message GenericVoidValue {}

// Anolog event
message AnalogEvent {
  int32 controller_id = 1;
  int64 timestamp = 2;
  float value = 3;
}

message ToggleEvent {
  int32 controller_id = 1;
  int64 timestamp = 2;
  bool value = 3;
}

message RelativeEvent {
  int32 controller_id = 1;
  int64 timestamp = 2;
  int32 value = 3;
}

message RangeEvent {
  int32 controller_id = 1;
  int64 timestamp = 2;
  int32 value = 3;
}

message Event {
  oneof event {
    AnalogEvent analog_ev = 1;
    ToggleEvent toggle_ev = 2;
    RelativeEvent relative_ev = 3;
    RangeEvent range_ev = 4;
  }
}

// Request to subscribe to events with optional filtering
message SubscribeRequest {
  // Optional: filter by specific controller IDs
  repeated int32 controller_ids = 1;
}

// Request to update the state of an Led 
message UpdateLedRequest {
  int32 led_id = 1;
  bool active = 2;
}

// Request to emit events for all pin states
message RefreshAllStatesRequest {}

// Response after emitting state events
message RefreshAllStatesResponse {
  repeated PotState pots = 1;
  repeated SwitchState switches = 2;
}

message PotState {
  string name = 1;
  double raw_value = 2;
  float normalized_value = 3;
  string device = 4;
  int32 id = 5;
}

message SwitchState {
  string name = 1;
  bool active = 2;
  string device = 3;
  int32 id = 4;
}

// Service definition
service PinProxyService {
  // Stream of pin events (server streaming)
  rpc SubscribeToEvents(SubscribeRequest) returns (stream Event);

  // Force emission of events for all pin states
  rpc RefreshAllStates(RefreshAllStatesRequest) returns (RefreshAllStatesResponse);

  // Write to leds
  rpc UpdateLed(UpdateLedRequest) returns (GenericVoidValue);
}
