# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sensei_rpc_pb2 as sensei__rpc__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensei_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SenseiControllerStub:
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToEvents = channel.unary_stream(
                '/sensei_rpc.SenseiController/SubscribeToEvents',
                request_serializer=sensei__rpc__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=sensei__rpc__pb2.Event.FromString,
                _registered_method=True)
        self.RefreshAllStates = channel.unary_unary(
                '/sensei_rpc.SenseiController/RefreshAllStates',
                request_serializer=sensei__rpc__pb2.GenericVoidValue.SerializeToString,
                response_deserializer=sensei__rpc__pb2.GenericVoidValue.FromString,
                _registered_method=True)
        self.GetControllerMap = channel.unary_unary(
                '/sensei_rpc.SenseiController/GetControllerMap',
                request_serializer=sensei__rpc__pb2.GenericVoidValue.SerializeToString,
                response_deserializer=sensei__rpc__pb2.GetControllerMapResponse.FromString,
                _registered_method=True)
        self.UpdateLed = channel.unary_unary(
                '/sensei_rpc.SenseiController/UpdateLed',
                request_serializer=sensei__rpc__pb2.UpdateLedRequest.SerializeToString,
                response_deserializer=sensei__rpc__pb2.GenericVoidValue.FromString,
                _registered_method=True)
        self.WriteToDisplay = channel.unary_unary(
                '/sensei_rpc.SenseiController/WriteToDisplay',
                request_serializer=sensei__rpc__pb2.WriteToDisplayRequest.SerializeToString,
                response_deserializer=sensei__rpc__pb2.GenericVoidValue.FromString,
                _registered_method=True)


class SenseiControllerServicer:
    """Service definition
    """

    def SubscribeToEvents(self, request, context):
        """Stream of pin events (server streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshAllStates(self, request, context):
        """Force emission of events for all pin states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControllerMap(self, request, context):
        """Get a list of all controller_id <-> name mappings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLed(self, request, context):
        """Write to leds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToDisplay(self, request, context):
        """Write to OLED display
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SenseiControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToEvents,
                    request_deserializer=sensei__rpc__pb2.SubscribeRequest.FromString,
                    response_serializer=sensei__rpc__pb2.Event.SerializeToString,
            ),
            'RefreshAllStates': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshAllStates,
                    request_deserializer=sensei__rpc__pb2.GenericVoidValue.FromString,
                    response_serializer=sensei__rpc__pb2.GenericVoidValue.SerializeToString,
            ),
            'GetControllerMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerMap,
                    request_deserializer=sensei__rpc__pb2.GenericVoidValue.FromString,
                    response_serializer=sensei__rpc__pb2.GetControllerMapResponse.SerializeToString,
            ),
            'UpdateLed': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLed,
                    request_deserializer=sensei__rpc__pb2.UpdateLedRequest.FromString,
                    response_serializer=sensei__rpc__pb2.GenericVoidValue.SerializeToString,
            ),
            'WriteToDisplay': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToDisplay,
                    request_deserializer=sensei__rpc__pb2.WriteToDisplayRequest.FromString,
                    response_serializer=sensei__rpc__pb2.GenericVoidValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensei_rpc.SenseiController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensei_rpc.SenseiController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SenseiController:
    """Service definition
    """

    @staticmethod
    def SubscribeToEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensei_rpc.SenseiController/SubscribeToEvents',
            sensei__rpc__pb2.SubscribeRequest.SerializeToString,
            sensei__rpc__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshAllStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensei_rpc.SenseiController/RefreshAllStates',
            sensei__rpc__pb2.GenericVoidValue.SerializeToString,
            sensei__rpc__pb2.GenericVoidValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControllerMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensei_rpc.SenseiController/GetControllerMap',
            sensei__rpc__pb2.GenericVoidValue.SerializeToString,
            sensei__rpc__pb2.GetControllerMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensei_rpc.SenseiController/UpdateLed',
            sensei__rpc__pb2.UpdateLedRequest.SerializeToString,
            sensei__rpc__pb2.GenericVoidValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteToDisplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensei_rpc.SenseiController/WriteToDisplay',
            sensei__rpc__pb2.WriteToDisplayRequest.SerializeToString,
            sensei__rpc__pb2.GenericVoidValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
